CELL_SIZE = 32
HUD_HEIGHT = 70

GAME_TICK_MS = 120

STARTING_LIVES = 3
CRYSTAL_POINTS = 100
LEVEL_COMPLETE_BONUS = 250

PLAYER_COLOR = "gold"
WALL_COLOR = "midnight blue"
PATH_COLOR = "black"
CRYSTAL_COLOR = "cyan"
TRAP_COLOR = "tomato"
EXIT_COLOR = "lime green"
TEXT_COLOR = "white"

DEFAULT_TIME_LIMIT = 45
LEVEL_TIME_LIMITS = [45, 50, 55, 60]