CELL_SIZE = 28
HUD_HEIGHT = 60

PLAYER_STEP_MS = 140
SHADOW_STEP_MS = 240

STARTING_LIVES = 3
ORB_POINTS = 10
ENERGY_POINTS = 50
SHADOW_BONUS = 200
LEVEL_COMPLETE_BONUS = 500
ENERGY_TICKS = 35

PLAYER_COLOR = "gold"
SHADOW_COLOR = "purple"
WALL_COLOR = "navy"
FLOOR_COLOR = "black"
ORB_COLOR = "white"
ENERGY_COLOR = "cyan"
EXIT_COLOR = "green"
TEXT_COLOR = "white"